
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: snwdb
  password: 12345
  host: localhost
  port: 5432


development:
  <<: *default
  database: snwror_development
  
test:
  <<: *default
  database: snwror_test

production:
  <<: *default
  database: snwror_production
  username: snwror
  password: <%= ENV['SNWROR_DATABASE_PASSWORD'] %>
